import './globals.scss'
import Header from "@/app/components/Header/Header";
import Footer from "@/app/components/Footer/Footer";
import React from "react";

export const metadata = {
  title: 'NextJS Technical Assessment',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  )
}
